### ISSUE TITLE
Excuse me, is there any reference that I can cite ?

### ISSUE THREAD

**Issue by lixingang** [TeamHG-Memex/eli5#400]
like this:

Fan A, Jernite Y, Perez E, et al. Eli5: Long form question answering[J]. arXiv preprint arXiv:1907.09190, 2019.

**Comment by lopuhin** [comment]
Not at the moment, please see https://github.com/TeamHG-Memex/eli5/issues/352

**Comment by lixingang** [comment]
> Not at the moment, please see #352

tks
