### ISSUE TITLE
some of IPython notebooks are broken

### ISSUE THREAD

**Issue by kmike** [TeamHG-Memex/eli5#73]
These notebooks got broken after we switched to `@attrs` instead of using dicts for explanation results:

* https://github.com/TeamHG-Memex/eli5/blob/master/notebooks/explain_text_prediction_char.ipynb
* https://github.com/TeamHG-Memex/eli5/blob/master/notebooks/explain_text_prediction_unhashing.ipynb

**Comment by lopuhin** [comment]
Right, I forgot to update them, let me fix them
